# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ObsAppJbDBDB.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QFrame,
    QGraphicsView, QGroupBox, QLabel, QLineEdit,
    QProgressBar, QPushButton, QRadioButton, QSizePolicy,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(842, 575)
        self.groupBox_18 = QGroupBox(Dialog)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(10, 10, 241, 331))
        font = QFont()
        font.setPointSize(8)
        self.groupBox_18.setFont(font)
        self.label_61 = QLabel(self.groupBox_18)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(10, 40, 111, 20))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(False)
        self.label_61.setFont(font1)
        self.label_61.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_62 = QLabel(self.groupBox_18)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(130, 40, 101, 20))
        self.label_62.setFont(font1)
        self.label_62.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_63 = QLabel(self.groupBox_18)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(10, 60, 111, 20))
        self.label_63.setFont(font1)
        self.label_63.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_64 = QLabel(self.groupBox_18)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(130, 60, 101, 20))
        self.label_64.setFont(font1)
        self.label_64.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_65 = QLabel(self.groupBox_18)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(10, 80, 111, 20))
        self.label_65.setFont(font1)
        self.label_65.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_66 = QLabel(self.groupBox_18)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(130, 80, 101, 20))
        self.label_66.setFont(font1)
        self.label_66.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_67 = QLabel(self.groupBox_18)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(10, 100, 111, 20))
        self.label_67.setFont(font1)
        self.label_67.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_68 = QLabel(self.groupBox_18)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(130, 100, 101, 20))
        self.label_68.setFont(font1)
        self.label_68.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_69 = QLabel(self.groupBox_18)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(10, 120, 111, 20))
        self.label_69.setFont(font1)
        self.label_69.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_70 = QLabel(self.groupBox_18)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(130, 120, 101, 20))
        self.label_70.setFont(font1)
        self.label_70.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_71 = QLabel(self.groupBox_18)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(10, 150, 111, 20))
        self.label_71.setFont(font1)
        self.label_71.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_72 = QLabel(self.groupBox_18)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(130, 150, 101, 20))
        self.label_72.setFont(font1)
        self.label_72.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_73 = QLabel(self.groupBox_18)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(10, 180, 111, 20))
        self.label_73.setFont(font1)
        self.label_73.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_74 = QLabel(self.groupBox_18)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(130, 180, 101, 20))
        self.label_74.setFont(font1)
        self.label_74.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_75 = QLabel(self.groupBox_18)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(130, 220, 101, 20))
        self.label_75.setFont(font1)
        self.label_75.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_76 = QLabel(self.groupBox_18)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(130, 200, 101, 20))
        self.label_76.setFont(font1)
        self.label_76.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_77 = QLabel(self.groupBox_18)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(130, 240, 101, 20))
        self.label_77.setFont(font1)
        self.label_77.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_78 = QLabel(self.groupBox_18)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(130, 280, 101, 20))
        self.label_78.setFont(font1)
        self.label_78.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_79 = QLabel(self.groupBox_18)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(10, 260, 111, 20))
        self.label_79.setFont(font1)
        self.label_79.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_80 = QLabel(self.groupBox_18)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(130, 260, 101, 20))
        self.label_80.setFont(font1)
        self.label_80.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_81 = QLabel(self.groupBox_18)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(10, 200, 111, 20))
        self.label_81.setFont(font1)
        self.label_81.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_82 = QLabel(self.groupBox_18)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(10, 220, 111, 20))
        self.label_82.setFont(font1)
        self.label_82.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_83 = QLabel(self.groupBox_18)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(10, 240, 111, 20))
        self.label_83.setFont(font1)
        self.label_83.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_84 = QLabel(self.groupBox_18)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(10, 280, 111, 20))
        self.label_84.setFont(font1)
        self.label_84.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_85 = QLabel(self.groupBox_18)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(10, 10, 221, 20))
        font2 = QFont()
        font2.setPointSize(13)
        font2.setBold(True)
        self.label_85.setFont(font2)
        self.label_85.setAlignment(Qt.AlignCenter)
        self.graphicsView = QGraphicsView(Dialog)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(260, 14, 161, 151))
        self.graphicsView.setFont(font)
        self.graphicsView_2 = QGraphicsView(Dialog)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(420, 14, 161, 151))
        self.graphicsView_2.setFont(font)
        self.graphicsView_3 = QGraphicsView(Dialog)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(260, 160, 321, 321))
        self.graphicsView_3.setFont(font)
        self.graphicsView_6 = QGraphicsView(Dialog)
        self.graphicsView_6.setObjectName(u"graphicsView_6")
        self.graphicsView_6.setGeometry(QRect(260, 480, 321, 81))
        self.graphicsView_6.setFont(font)
        self.groupBox_19 = QGroupBox(Dialog)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(10, 360, 241, 201))
        self.groupBox_19.setFont(font)
        self.label_86 = QLabel(self.groupBox_19)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(10, 40, 101, 20))
        self.label_86.setFont(font1)
        self.label_86.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_87 = QLabel(self.groupBox_19)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(120, 40, 111, 20))
        self.label_87.setFont(font1)
        self.label_87.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_88 = QLabel(self.groupBox_19)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(10, 60, 101, 20))
        self.label_88.setFont(font1)
        self.label_88.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_89 = QLabel(self.groupBox_19)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(120, 60, 111, 20))
        self.label_89.setFont(font1)
        self.label_89.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_90 = QLabel(self.groupBox_19)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(10, 80, 141, 20))
        self.label_90.setFont(font1)
        self.label_90.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_91 = QLabel(self.groupBox_19)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setGeometry(QRect(160, 80, 71, 20))
        self.label_91.setFont(font1)
        self.label_91.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_92 = QLabel(self.groupBox_19)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(10, 100, 141, 20))
        self.label_92.setFont(font1)
        self.label_92.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_93 = QLabel(self.groupBox_19)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(160, 100, 71, 20))
        self.label_93.setFont(font1)
        self.label_93.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_94 = QLabel(self.groupBox_19)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(10, 120, 141, 20))
        self.label_94.setFont(font1)
        self.label_94.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_95 = QLabel(self.groupBox_19)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(160, 120, 71, 20))
        self.label_95.setFont(font1)
        self.label_95.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_110 = QLabel(self.groupBox_19)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setGeometry(QRect(10, 10, 221, 20))
        self.label_110.setFont(font2)
        self.label_110.setAlignment(Qt.AlignCenter)
        self.progressBar_2 = QProgressBar(self.groupBox_19)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(10, 160, 221, 20))
        self.progressBar_2.setFont(font)
        self.progressBar_2.setValue(24)
        self.label_96 = QLabel(self.groupBox_19)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(160, 140, 71, 20))
        self.label_96.setFont(font1)
        self.label_96.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_97 = QLabel(self.groupBox_19)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(10, 140, 141, 20))
        self.label_97.setFont(font1)
        self.label_97.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_20 = QGroupBox(Dialog)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setGeometry(QRect(590, 10, 241, 551))
        self.groupBox_20.setFont(font)
        self.label_112 = QLabel(self.groupBox_20)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setGeometry(QRect(10, 40, 101, 20))
        self.label_112.setFont(font1)
        self.label_112.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_113 = QLabel(self.groupBox_20)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setGeometry(QRect(120, 40, 111, 20))
        self.label_113.setFont(font1)
        self.label_113.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_114 = QLabel(self.groupBox_20)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setGeometry(QRect(10, 60, 101, 20))
        self.label_114.setFont(font1)
        self.label_114.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_115 = QLabel(self.groupBox_20)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setGeometry(QRect(120, 60, 111, 20))
        self.label_115.setFont(font1)
        self.label_115.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_116 = QLabel(self.groupBox_20)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setGeometry(QRect(10, 80, 141, 20))
        self.label_116.setFont(font1)
        self.label_116.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_117 = QLabel(self.groupBox_20)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setGeometry(QRect(160, 80, 71, 20))
        self.label_117.setFont(font1)
        self.label_117.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_118 = QLabel(self.groupBox_20)
        self.label_118.setObjectName(u"label_118")
        self.label_118.setGeometry(QRect(10, 100, 141, 20))
        self.label_118.setFont(font1)
        self.label_118.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_122 = QLabel(self.groupBox_20)
        self.label_122.setObjectName(u"label_122")
        self.label_122.setGeometry(QRect(10, 10, 221, 20))
        self.label_122.setFont(font2)
        self.label_122.setAlignment(Qt.AlignCenter)
        self.progressBar_4 = QProgressBar(self.groupBox_20)
        self.progressBar_4.setObjectName(u"progressBar_4")
        self.progressBar_4.setGeometry(QRect(10, 180, 221, 20))
        self.progressBar_4.setFont(font)
        self.progressBar_4.setValue(24)
        self.lineEdit_16 = QLineEdit(self.groupBox_20)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(160, 100, 61, 21))
        self.lineEdit_16.setFont(font)
        self.pushButton_15 = QPushButton(self.groupBox_20)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(10, 130, 141, 41))
        self.pushButton_15.setFont(font)
        self.pushButton_16 = QPushButton(self.groupBox_20)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(160, 130, 71, 41))
        self.pushButton_16.setFont(font)
        self.pushButton_18 = QPushButton(self.groupBox_20)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(160, 340, 71, 41))
        self.pushButton_18.setFont(font)
        self.pushButton_17 = QPushButton(self.groupBox_20)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(10, 340, 141, 41))
        self.pushButton_17.setFont(font)
        self.pushButton_29 = QPushButton(self.groupBox_20)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(120, 300, 111, 31))
        self.pushButton_29.setFont(font)
        self.line_7 = QFrame(self.groupBox_20)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 200, 221, 20))
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.label_47 = QLabel(self.groupBox_20)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(170, 240, 61, 20))
        font3 = QFont()
        font3.setPointSize(8)
        font3.setBold(False)
        self.label_47.setFont(font3)
        self.label_47.setLayoutDirection(Qt.LeftToRight)
        self.label_47.setAlignment(Qt.AlignCenter)
        self.label_46 = QLabel(self.groupBox_20)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(170, 220, 61, 20))
        self.label_46.setFont(font3)
        self.label_46.setLayoutDirection(Qt.LeftToRight)
        self.label_46.setAlignment(Qt.AlignCenter)
        self.label_49 = QLabel(self.groupBox_20)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(170, 280, 61, 20))
        self.label_49.setFont(font3)
        self.label_49.setLayoutDirection(Qt.LeftToRight)
        self.label_49.setAlignment(Qt.AlignCenter)
        self.label_45 = QLabel(self.groupBox_20)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(120, 240, 41, 20))
        self.label_45.setFont(font3)
        self.label_45.setLayoutDirection(Qt.LeftToRight)
        self.label_45.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_51 = QLabel(self.groupBox_20)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(120, 280, 41, 20))
        self.label_51.setFont(font3)
        self.label_51.setLayoutDirection(Qt.LeftToRight)
        self.label_51.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_50 = QLabel(self.groupBox_20)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(170, 260, 61, 20))
        self.label_50.setFont(font3)
        self.label_50.setLayoutDirection(Qt.LeftToRight)
        self.label_50.setAlignment(Qt.AlignCenter)
        self.label_48 = QLabel(self.groupBox_20)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(120, 260, 41, 20))
        self.label_48.setFont(font3)
        self.label_48.setLayoutDirection(Qt.LeftToRight)
        self.label_48.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_44 = QLabel(self.groupBox_20)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(120, 220, 41, 20))
        self.label_44.setFont(font3)
        self.label_44.setLayoutDirection(Qt.LeftToRight)
        self.label_44.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_5 = QPushButton(self.groupBox_20)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(40, 290, 31, 31))
        self.pushButton_5.setFont(font3)
        self.lineEdit_7 = QLineEdit(self.groupBox_20)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(40, 260, 31, 31))
        self.lineEdit_7.setFont(font3)
        self.pushButton_4 = QPushButton(self.groupBox_20)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(70, 260, 31, 31))
        self.pushButton_4.setFont(font3)
        self.pushButton_6 = QPushButton(self.groupBox_20)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(10, 260, 31, 31))
        self.pushButton_6.setFont(font3)
        self.pushButton_3 = QPushButton(self.groupBox_20)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(40, 230, 31, 31))
        self.pushButton_3.setFont(font3)
        self.line_8 = QFrame(self.groupBox_20)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(10, 440, 221, 20))
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.radioButton_5 = QRadioButton(self.groupBox_20)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(80, 460, 81, 21))
        self.radioButton_5.setFont(font)
        self.radioButton_3 = QRadioButton(self.groupBox_20)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(20, 460, 51, 21))
        self.radioButton_3.setFont(font)
        self.lineEdit_2 = QLineEdit(self.groupBox_20)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(90, 490, 61, 21))
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_4 = QLineEdit(self.groupBox_20)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(160, 520, 61, 21))
        self.lineEdit_4.setFont(font)
        self.radioButton = QRadioButton(self.groupBox_20)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(20, 490, 61, 21))
        self.radioButton.setFont(font)
        self.lineEdit_3 = QLineEdit(self.groupBox_20)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(160, 490, 61, 21))
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setReadOnly(True)
        self.radioButton_2 = QRadioButton(self.groupBox_20)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(20, 520, 71, 21))
        self.radioButton_2.setFont(font)
        self.lineEdit = QLineEdit(self.groupBox_20)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(90, 520, 61, 21))
        self.lineEdit.setFont(font)
        self.label_41 = QLabel(self.groupBox_20)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 390, 81, 20))
        self.label_41.setFont(font3)
        self.label_41.setLayoutDirection(Qt.LeftToRight)
        self.label_41.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_3 = QComboBox(self.groupBox_20)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(100, 390, 131, 21))
        self.comboBox_3.setFont(font)
        self.label_42 = QLabel(self.groupBox_20)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 420, 81, 20))
        self.label_42.setFont(font3)
        self.label_42.setLayoutDirection(Qt.LeftToRight)
        self.label_42.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_4 = QComboBox(self.groupBox_20)
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(100, 420, 131, 21))
        self.comboBox_4.setFont(font)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.groupBox_18.setTitle("")
        self.label_61.setText(QCoreApplication.translate("Dialog", u"IGRINS-2 Health:", None))
        self.label_62.setText(QCoreApplication.translate("Dialog", u"GOOD", None))
        self.label_63.setText(QCoreApplication.translate("Dialog", u"GDSN Status:", None))
        self.label_64.setText(QCoreApplication.translate("Dialog", u"Disconnected", None))
        self.label_65.setText(QCoreApplication.translate("Dialog", u"GMP Status:", None))
        self.label_66.setText(QCoreApplication.translate("Dialog", u"Disconnected", None))
        self.label_67.setText(QCoreApplication.translate("Dialog", u"State:", None))
        self.label_68.setText(QCoreApplication.translate("Dialog", u"Running", None))
        self.label_69.setText(QCoreApplication.translate("Dialog", u"Action State:", None))
        self.label_70.setText(QCoreApplication.translate("Dialog", u"Idle", None))
        self.label_71.setText(QCoreApplication.translate("Dialog", u"Press (Torr):", None))
        self.label_72.setText(QCoreApplication.translate("Dialog", u"9.99e+1", None))
        self.label_73.setText(QCoreApplication.translate("Dialog", u"Det H (K):", None))
        self.label_74.setText(QCoreApplication.translate("Dialog", u"65.0", None))
        self.label_75.setText(QCoreApplication.translate("Dialog", u"65.0", None))
        self.label_76.setText(QCoreApplication.translate("Dialog", u"65.0", None))
        self.label_77.setText(QCoreApplication.translate("Dialog", u"50", None))
        self.label_78.setText(QCoreApplication.translate("Dialog", u"50", None))
        self.label_79.setText(QCoreApplication.translate("Dialog", u"Heater K (%):", None))
        self.label_80.setText(QCoreApplication.translate("Dialog", u"50", None))
        self.label_81.setText(QCoreApplication.translate("Dialog", u"Det K (K):", None))
        self.label_82.setText(QCoreApplication.translate("Dialog", u"Det S (K):", None))
        self.label_83.setText(QCoreApplication.translate("Dialog", u"Heater H (%):", None))
        self.label_84.setText(QCoreApplication.translate("Dialog", u"Heater S (%):", None))
        self.label_85.setText(QCoreApplication.translate("Dialog", u"Instrument Status", None))
        self.groupBox_19.setTitle("")
        self.label_86.setText(QCoreApplication.translate("Dialog", u"Data Label:", None))
        self.label_87.setText(QCoreApplication.translate("Dialog", u"S20221020S0001", None))
        self.label_88.setText(QCoreApplication.translate("Dialog", u"Observing State:", None))
        self.label_89.setText(QCoreApplication.translate("Dialog", u"---", None))
        self.label_90.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.label_91.setText(QCoreApplication.translate("Dialog", u"16", None))
        self.label_92.setText(QCoreApplication.translate("Dialog", u"Exposure Time (sec):", None))
        self.label_93.setText(QCoreApplication.translate("Dialog", u"123456.32", None))
        self.label_94.setText(QCoreApplication.translate("Dialog", u"Time Left:", None))
        self.label_95.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.label_110.setText(QCoreApplication.translate("Dialog", u"Science Observation", None))
        self.label_96.setText(QCoreApplication.translate("Dialog", u"90", None))
        self.label_97.setText(QCoreApplication.translate("Dialog", u"IPA (deg):", None))
        self.groupBox_20.setTitle("")
        self.label_112.setText(QCoreApplication.translate("Dialog", u"Data Label:", None))
        self.label_113.setText(QCoreApplication.translate("Dialog", u"S20221020S0001", None))
        self.label_114.setText(QCoreApplication.translate("Dialog", u"Observing State:", None))
        self.label_115.setText(QCoreApplication.translate("Dialog", u"---", None))
        self.label_116.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.label_117.setText(QCoreApplication.translate("Dialog", u"16", None))
        self.label_118.setText(QCoreApplication.translate("Dialog", u"Exposure Time (sec):", None))
        self.label_122.setText(QCoreApplication.translate("Dialog", u"Slit View Camera", None))
        self.pushButton_15.setText(QCoreApplication.translate("Dialog", u"Single", None))
        self.pushButton_16.setText(QCoreApplication.translate("Dialog", u"Stop", None))
        self.pushButton_18.setText(QCoreApplication.translate("Dialog", u"Stop\n"
"Guide", None))
        self.pushButton_17.setText(QCoreApplication.translate("Dialog", u"Guide", None))
        self.pushButton_29.setText(QCoreApplication.translate("Dialog", u"Select Guide Star", None))
        self.label_47.setText(QCoreApplication.translate("Dialog", u"0.0", None))
        self.label_46.setText(QCoreApplication.translate("Dialog", u"0.0", None))
        self.label_49.setText(QCoreApplication.translate("Dialog", u"0.0", None))
        self.label_45.setText(QCoreApplication.translate("Dialog", u"dDec", None))
        self.label_51.setText(QCoreApplication.translate("Dialog", u"Y=", None))
        self.label_50.setText(QCoreApplication.translate("Dialog", u"0.0", None))
        self.label_48.setText(QCoreApplication.translate("Dialog", u"X=", None))
        self.label_44.setText(QCoreApplication.translate("Dialog", u"dRA", None))
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"S", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"W", None))
        self.pushButton_6.setText(QCoreApplication.translate("Dialog", u"E", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"N", None))
        self.radioButton_5.setText(QCoreApplication.translate("Dialog", u"Sub(Sky)", None))
        self.radioButton_3.setText(QCoreApplication.translate("Dialog", u"Raw", None))
        self.radioButton.setText(QCoreApplication.translate("Dialog", u"Zscale", None))
        self.radioButton_2.setText(QCoreApplication.translate("Dialog", u"Manual", None))
        self.label_41.setText(QCoreApplication.translate("Dialog", u"Center Finding", None))
        self.label_42.setText(QCoreApplication.translate("Dialog", u"FHWM mode", None))
    # retranslateUi

