# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SCPRjHUlP.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QFrame,
    QGraphicsView, QGroupBox, QLabel, QLineEdit,
    QProgressBar, QPushButton, QRadioButton, QSizePolicy,
    QVBoxLayout, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(712, 681)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        #Dialog.setSizeGripEnabled(False)
        self.groupBox_5 = QGroupBox(Dialog)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(430, 580, 271, 91))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.groupBox_5.setFont(font)
        self.radioButton_zscale = QRadioButton(self.groupBox_5)
        self.radioButton_zscale.setObjectName(u"radioButton_zscale")
        self.radioButton_zscale.setGeometry(QRect(10, 30, 61, 21))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(True)
        self.radioButton_zscale.setFont(font1)
        self.radioButton_mscale = QRadioButton(self.groupBox_5)
        self.radioButton_mscale.setObjectName(u"radioButton_mscale")
        self.radioButton_mscale.setGeometry(QRect(10, 60, 71, 21))
        self.radioButton_mscale.setFont(font1)
        self.e_mscale_min = QLineEdit(self.groupBox_5)
        self.e_mscale_min.setObjectName(u"e_mscale_min")
        self.e_mscale_min.setGeometry(QRect(90, 60, 51, 21))
        self.e_mscale_min.setFont(font1)
        self.e_mscale_min.setAlignment(Qt.AlignCenter)
        self.e_mscale_max = QLineEdit(self.groupBox_5)
        self.e_mscale_max.setObjectName(u"e_mscale_max")
        self.e_mscale_max.setGeometry(QRect(150, 60, 51, 21))
        self.e_mscale_max.setFont(font1)
        self.e_mscale_max.setAlignment(Qt.AlignCenter)
        self.bt_scale_apply = QPushButton(self.groupBox_5)
        self.bt_scale_apply.setObjectName(u"bt_scale_apply")
        self.bt_scale_apply.setGeometry(QRect(210, 60, 51, 21))
        self.bt_scale_apply.setFont(font1)
        self.label_zscale_range = QLabel(self.groupBox_5)
        self.label_zscale_range.setObjectName(u"label_zscale_range")
        self.label_zscale_range.setGeometry(QRect(90, 30, 111, 20))
        font2 = QFont()
        font2.setPointSize(8)
        font2.setBold(False)
        self.label_zscale_range.setFont(font2)
        self.label_zscale_range.setLayoutDirection(Qt.LeftToRight)
        self.label_zscale_range.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.groupBox_6 = QGroupBox(Dialog)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(430, 10, 271, 161))
        self.groupBox_6.setFont(font)
        self.label_7 = QLabel(self.groupBox_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 71, 20))
        self.label_7.setFont(font1)
        self.label_7.setLayoutDirection(Qt.LeftToRight)
        self.label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_9 = QLabel(self.groupBox_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 100, 81, 20))
        self.label_9.setFont(font1)
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_dec = QLabel(self.groupBox_6)
        self.label_dec.setObjectName(u"label_dec")
        self.label_dec.setGeometry(QRect(180, 30, 91, 20))
        self.label_dec.setFont(font2)
        self.label_dec.setLayoutDirection(Qt.LeftToRight)
        self.label_dec.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_dcss_sts = QLabel(self.groupBox_6)
        self.label_dcss_sts.setObjectName(u"label_dcss_sts")
        self.label_dcss_sts.setGeometry(QRect(90, 100, 91, 20))
        self.label_dcss_sts.setFont(font2)
        self.label_dcss_sts.setLayoutDirection(Qt.LeftToRight)
        self.label_dcss_sts.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_ra = QLabel(self.groupBox_6)
        self.label_ra.setObjectName(u"label_ra")
        self.label_ra.setGeometry(QRect(90, 30, 91, 20))
        self.label_ra.setFont(font2)
        self.label_ra.setLayoutDirection(Qt.LeftToRight)
        self.label_ra.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_airmass = QLabel(self.groupBox_6)
        self.label_airmass.setObjectName(u"label_airmass")
        self.label_airmass.setGeometry(QRect(90, 50, 41, 20))
        self.label_airmass.setFont(font2)
        self.label_airmass.setLayoutDirection(Qt.LeftToRight)
        self.label_airmass.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_14 = QLabel(self.groupBox_6)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 50, 81, 20))
        self.label_14.setFont(font1)
        self.label_14.setLayoutDirection(Qt.LeftToRight)
        self.label_14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_15 = QLabel(self.groupBox_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 120, 81, 20))
        self.label_15.setFont(font1)
        self.label_15.setLayoutDirection(Qt.LeftToRight)
        self.label_15.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_mode = QLabel(self.groupBox_6)
        self.label_mode.setObjectName(u"label_mode")
        self.label_mode.setGeometry(QRect(90, 120, 91, 20))
        self.label_mode.setFont(font2)
        self.label_mode.setLayoutDirection(Qt.LeftToRight)
        self.label_mode.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.bt_DCSS_check = QPushButton(self.groupBox_6)
        self.bt_DCSS_check.setObjectName(u"bt_DCSS_check")
        self.bt_DCSS_check.setGeometry(QRect(180, 100, 41, 21))
        self.bt_DCSS_check.setFont(font1)
        self.bt_DCSS_check_stop = QPushButton(self.groupBox_6)
        self.bt_DCSS_check_stop.setObjectName(u"bt_DCSS_check_stop")
        self.bt_DCSS_check_stop.setGeometry(QRect(220, 100, 41, 21))
        self.bt_DCSS_check_stop.setFont(font1)
        self.label_MQserver_sts = QLabel(self.groupBox_6)
        self.label_MQserver_sts.setObjectName(u"label_MQserver_sts")
        self.label_MQserver_sts.setGeometry(QRect(90, 80, 91, 20))
        self.label_MQserver_sts.setFont(font2)
        self.label_MQserver_sts.setLayoutDirection(Qt.LeftToRight)
        self.label_MQserver_sts.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_10 = QLabel(self.groupBox_6)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 80, 81, 20))
        self.label_10.setFont(font1)
        self.label_10.setLayoutDirection(Qt.LeftToRight)
        self.label_10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_MQserver_retry = QPushButton(self.groupBox_6)
        self.bt_MQserver_retry.setObjectName(u"bt_MQserver_retry")
        self.bt_MQserver_retry.setGeometry(QRect(180, 80, 41, 21))
        self.bt_MQserver_retry.setFont(font1)
        self.bt_DCSS_init = QPushButton(self.groupBox_6)
        self.bt_DCSS_init.setObjectName(u"bt_DCSS_init")
        self.bt_DCSS_init.setGeometry(QRect(180, 120, 81, 21))
        self.bt_DCSS_init.setFont(font1)
        self.groupBox_8 = QGroupBox(Dialog)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(430, 180, 271, 271))
        self.groupBox_8.setFont(font)
        self.bt_acquisition = QPushButton(self.groupBox_8)
        self.bt_acquisition.setObjectName(u"bt_acquisition")
        self.bt_acquisition.setGeometry(QRect(10, 120, 81, 41))
        self.bt_acquisition.setFont(font1)
        self.bt_stop = QPushButton(self.groupBox_8)
        self.bt_stop.setObjectName(u"bt_stop")
        self.bt_stop.setGeometry(QRect(100, 120, 41, 41))
        self.bt_stop.setFont(font1)
        self.line_5 = QFrame(self.groupBox_8)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(140, 120, 20, 41))
        self.line_5.setFont(font1)
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_19 = QLabel(self.groupBox_8)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(160, 120, 41, 20))
        self.label_19.setFont(font1)
        self.label_19.setLayoutDirection(Qt.LeftToRight)
        self.label_19.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_repeat_number = QLineEdit(self.groupBox_8)
        self.e_repeat_number.setObjectName(u"e_repeat_number")
        self.e_repeat_number.setGeometry(QRect(210, 120, 41, 21))
        self.e_repeat_number.setFont(font1)
        self.e_repeat_number.setAlignment(Qt.AlignCenter)
        self.label_38 = QLabel(self.groupBox_8)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(0, 90, 61, 20))
        self.label_38.setFont(font1)
        self.label_38.setLayoutDirection(Qt.LeftToRight)
        self.label_38.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_exptime = QLineEdit(self.groupBox_8)
        self.e_exptime.setObjectName(u"e_exptime")
        self.e_exptime.setGeometry(QRect(70, 90, 51, 21))
        self.e_exptime.setFont(font1)
        self.e_exptime.setAlignment(Qt.AlignCenter)
        self.label_39 = QLabel(self.groupBox_8)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(120, 90, 101, 20))
        self.label_39.setFont(font1)
        self.label_39.setLayoutDirection(Qt.LeftToRight)
        self.label_39.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_FS_number = QLineEdit(self.groupBox_8)
        self.e_FS_number.setObjectName(u"e_FS_number")
        self.e_FS_number.setGeometry(QRect(230, 90, 31, 21))
        self.e_FS_number.setFont(font1)
        self.e_FS_number.setAlignment(Qt.AlignCenter)
        self.line_7 = QFrame(self.groupBox_8)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 160, 251, 20))
        self.line_7.setFont(font1)
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.label_29 = QLabel(self.groupBox_8)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 180, 71, 20))
        self.label_29.setFont(font1)
        self.label_29.setLayoutDirection(Qt.LeftToRight)
        self.label_29.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_stats = QLabel(self.groupBox_8)
        self.label_prog_stats.setObjectName(u"label_prog_stats")
        self.label_prog_stats.setGeometry(QRect(90, 180, 171, 20))
        palette = QPalette()
        self.label_prog_stats.setPalette(palette)
        self.label_prog_stats.setFont(font2)
        self.label_prog_stats.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_stats.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_25 = QLabel(self.groupBox_8)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 200, 71, 20))
        self.label_25.setFont(font1)
        self.label_25.setLayoutDirection(Qt.LeftToRight)
        self.label_25.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.progressBar = QProgressBar(self.groupBox_8)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(20, 240, 191, 20))
        self.progressBar.setFont(font1)
        self.progressBar.setValue(24)
        self.label_28 = QLabel(self.groupBox_8)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 220, 71, 20))
        self.label_28.setFont(font1)
        self.label_28.setLayoutDirection(Qt.LeftToRight)
        self.label_28.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_time = QLabel(self.groupBox_8)
        self.label_prog_time.setObjectName(u"label_prog_time")
        self.label_prog_time.setGeometry(QRect(90, 200, 171, 20))
        self.label_prog_time.setFont(font2)
        self.label_prog_time.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_time.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_prog_elapsed = QLabel(self.groupBox_8)
        self.label_prog_elapsed.setObjectName(u"label_prog_elapsed")
        self.label_prog_elapsed.setGeometry(QRect(90, 220, 61, 20))
        self.label_prog_elapsed.setFont(font2)
        self.label_prog_elapsed.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_elapsed.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_31 = QLabel(self.groupBox_8)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(220, 240, 51, 20))
        self.label_31.setFont(font2)
        self.label_31.setLayoutDirection(Qt.LeftToRight)
        self.label_31.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_cur_num = QLabel(self.groupBox_8)
        self.label_cur_num.setObjectName(u"label_cur_num")
        self.label_cur_num.setGeometry(QRect(160, 140, 91, 20))
        self.label_cur_num.setFont(font2)
        self.label_cur_num.setLayoutDirection(Qt.LeftToRight)
        self.label_cur_num.setAlignment(Qt.AlignCenter)
        self.chk_ROI_mode = QCheckBox(self.groupBox_8)
        self.chk_ROI_mode.setObjectName(u"chk_ROI_mode")
        self.chk_ROI_mode.setGeometry(QRect(12, 26, 81, 21))
        self.chk_ROI_mode.setFont(font1)
        self.e_boxsize = QLineEdit(self.groupBox_8)
        self.e_boxsize.setObjectName(u"e_boxsize")
        self.e_boxsize.setGeometry(QRect(160, 26, 31, 21))
        self.e_boxsize.setFont(font1)
        self.e_boxsize.setAlignment(Qt.AlignCenter)
        self.label_40 = QLabel(self.groupBox_8)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(89, 26, 61, 20))
        self.label_40.setFont(font1)
        self.label_40.setLayoutDirection(Qt.LeftToRight)
        self.label_40.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_ROI_SET = QPushButton(self.groupBox_8)
        self.bt_ROI_SET.setObjectName(u"bt_ROI_SET")
        self.bt_ROI_SET.setGeometry(QRect(200, 26, 51, 21))
        self.bt_ROI_SET.setFont(font1)
        self.label_ROI_center = QLabel(self.groupBox_8)
        self.label_ROI_center.setObjectName(u"label_ROI_center")
        self.label_ROI_center.setGeometry(QRect(181, 52, 81, 21))
        self.label_ROI_center.setFont(font2)
        self.label_ROI_center.setLayoutDirection(Qt.LeftToRight)
        self.label_ROI_center.setAlignment(Qt.AlignCenter)
        self.line_8 = QFrame(self.groupBox_8)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(10, 70, 251, 20))
        self.line_8.setFont(font1)
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.label_cur_cursor = QLabel(self.groupBox_8)
        self.label_cur_cursor.setObjectName(u"label_cur_cursor")
        self.label_cur_cursor.setGeometry(QRect(9, 52, 141, 21))
        self.label_cur_cursor.setFont(font2)
        self.label_cur_cursor.setLayoutDirection(Qt.LeftToRight)
        self.label_cur_cursor.setAlignment(Qt.AlignCenter)
        self.label_prog_time_4 = QLabel(self.groupBox_8)
        self.label_prog_time_4.setObjectName(u"label_prog_time_4")
        self.label_prog_time_4.setGeometry(QRect(150, 52, 31, 21))
        self.label_prog_time_4.setFont(font2)
        self.label_prog_time_4.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_time_4.setAlignment(Qt.AlignCenter)
        self.groupBox_12 = QGroupBox(Dialog)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(430, 460, 271, 111))
        self.groupBox_12.setFont(font)
        self.checkBox_compress = QCheckBox(self.groupBox_12)
        self.checkBox_compress.setObjectName(u"checkBox_compress")
        self.checkBox_compress.setGeometry(QRect(10, 30, 81, 21))
        self.checkBox_compress.setFont(font1)
        self.checkBox_autosave = QCheckBox(self.groupBox_12)
        self.checkBox_autosave.setObjectName(u"checkBox_autosave")
        self.checkBox_autosave.setGeometry(QRect(90, 30, 131, 21))
        self.checkBox_autosave.setFont(font1)
        self.bt_path = QPushButton(self.groupBox_12)
        self.bt_path.setObjectName(u"bt_path")
        self.bt_path.setGeometry(QRect(10, 60, 51, 21))
        self.bt_path.setFont(font1)
        self.e_savepath = QLineEdit(self.groupBox_12)
        self.e_savepath.setObjectName(u"e_savepath")
        self.e_savepath.setGeometry(QRect(70, 60, 191, 21))
        self.e_savepath.setFont(font1)
        self.label_52 = QLabel(self.groupBox_12)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(0, 80, 61, 20))
        self.label_52.setFont(font2)
        self.label_52.setLayoutDirection(Qt.LeftToRight)
        self.label_52.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_save = QPushButton(self.groupBox_12)
        self.bt_save.setObjectName(u"bt_save")
        self.bt_save.setGeometry(QRect(220, 30, 41, 21))
        self.bt_save.setFont(font1)
        self.e_savefilename = QLineEdit(self.groupBox_12)
        self.e_savefilename.setObjectName(u"e_savefilename")
        self.e_savefilename.setGeometry(QRect(70, 80, 191, 21))
        self.e_savefilename.setFont(font1)
        self.graphicsView_main = QGraphicsView(Dialog)
        self.graphicsView_main.setObjectName(u"graphicsView_main")
        self.graphicsView_main.setGeometry(QRect(10, 260, 411, 411))
        self.graphicsView_main.setFont(font1)
        self.graphicsView_main.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.graphicsView_main.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 240, 121, 19))
        self.label.setFont(font)
        self.graphicsView_roi = QGraphicsView(Dialog)
        self.graphicsView_roi.setObjectName(u"graphicsView_roi")
        self.graphicsView_roi.setGeometry(QRect(10, 30, 201, 201))
        self.graphicsView_roi.setFont(font1)
        self.graphicsView_roi.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.graphicsView_roi.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 111, 19))
        self.label_2.setFont(font)
        self.verticalLayoutWidget = QWidget(Dialog)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(220, 29, 201, 201))
        self.graph_vertical_radial = QVBoxLayout(self.verticalLayoutWidget)
        self.graph_vertical_radial.setObjectName(u"graph_vertical_radial")
        self.graph_vertical_radial.setContentsMargins(0, 0, 0, 0)
        self.label_graph_radial = QLabel(Dialog)
        self.label_graph_radial.setObjectName(u"label_graph_radial")
        self.label_graph_radial.setGeometry(QRect(220, 30, 201, 201))
        self.label_graph_radial.setFrameShape(QFrame.StyledPanel)
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 10, 131, 19))
        self.label_3.setFont(font)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Slit Camera Package", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Dialog", u"Scaling Mode", None))
        self.radioButton_zscale.setText(QCoreApplication.translate("Dialog", u"Zscale", None))
        self.radioButton_mscale.setText(QCoreApplication.translate("Dialog", u"Manual", None))
        self.bt_scale_apply.setText(QCoreApplication.translate("Dialog", u"Apply", None))
        self.label_zscale_range.setText(QCoreApplication.translate("Dialog", u"0 ~ 1000", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Dialog", u"Information", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"RA / Dec :", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"DCSS:", None))
        self.label_dec.setText(QCoreApplication.translate("Dialog", u"00:00:00.0", None))
        self.label_dcss_sts.setText(QCoreApplication.translate("Dialog", u"---", None))
        self.label_ra.setText(QCoreApplication.translate("Dialog", u"+00:00:00.00", None))
        self.label_airmass.setText(QCoreApplication.translate("Dialog", u"0.000", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"airmass :", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Mode:", None))
        self.label_mode.setText(QCoreApplication.translate("Dialog", u"Simulation/Real", None))
        self.bt_DCSS_check.setText(QCoreApplication.translate("Dialog", u"Check", None))
        self.bt_DCSS_check_stop.setText(QCoreApplication.translate("Dialog", u"Stop", None))
        self.label_MQserver_sts.setText(QCoreApplication.translate("Dialog", u"---", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"MQ Server:", None))
        self.bt_MQserver_retry.setText(QCoreApplication.translate("Dialog", u"Retry", None))
        self.bt_DCSS_init.setText(QCoreApplication.translate("Dialog", u"DCSS Init", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("Dialog", u"Image Taking Mode", None))
        self.bt_acquisition.setText(QCoreApplication.translate("Dialog", u"Acquisition", None))
        self.bt_stop.setText(QCoreApplication.translate("Dialog", u"Stop", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Repeat:", None))
        self.label_38.setText(QCoreApplication.translate("Dialog", u"Exp. Time:", None))
        self.label_39.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"Status :", None))
        self.label_prog_stats.setText(QCoreApplication.translate("Dialog", u"START/END/TRANSFER/DONE", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Start/End :", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Elapsed :", None))
        self.label_prog_time.setText(QCoreApplication.translate("Dialog", u"00:00:00.0 / 00:00:00.0", None))
        self.label_prog_elapsed.setText(QCoreApplication.translate("Dialog", u"0.0 sec", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"\\ 16MB", None))
        self.label_cur_num.setText(QCoreApplication.translate("Dialog", u"1 / 1", None))
        self.chk_ROI_mode.setText(QCoreApplication.translate("Dialog", u"ROI mode", None))
        self.label_40.setText(QCoreApplication.translate("Dialog", u"Box size:", None))
        self.bt_ROI_SET.setText(QCoreApplication.translate("Dialog", u"ROI SET", None))
        self.label_ROI_center.setText(QCoreApplication.translate("Dialog", u"( x , y )", None))
        self.label_cur_cursor.setText(QCoreApplication.translate("Dialog", u"( x , y )", None))
        self.label_prog_time_4.setText(QCoreApplication.translate("Dialog", u">>>", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("Dialog", u"Image Storage", None))
        self.checkBox_compress.setText(QCoreApplication.translate("Dialog", u"Compress", None))
        self.checkBox_autosave.setText(QCoreApplication.translate("Dialog", u"Automatically Save", None))
        self.bt_path.setText(QCoreApplication.translate("Dialog", u"Path", None))
        self.label_52.setText(QCoreApplication.translate("Dialog", u"File name", None))
        self.bt_save.setText(QCoreApplication.translate("Dialog", u"SAVE", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Image Window", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Zoom-in Box", None))
        self.label_graph_radial.setText("")
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Gaussian-fitting", None))
    # retranslateUi

