# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'maciecPGACc.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QGroupBox, QLabel,
    QLineEdit, QPushButton, QRadioButton, QSizePolicy,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(432, 352)
        self.bt_initialize1 = QPushButton(Dialog)
        self.bt_initialize1.setObjectName(u"bt_initialize1")
        self.bt_initialize1.setGeometry(QRect(10, 110, 91, 41))
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.bt_initialize1.setFont(font)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 151, 81))
        font1 = QFont()
        font1.setPointSize(10)
        self.groupBox.setFont(font1)
        self.bt_pwr_on = QPushButton(self.groupBox)
        self.bt_pwr_on.setObjectName(u"bt_pwr_on")
        self.bt_pwr_on.setGeometry(QRect(10, 40, 61, 31))
        self.bt_pwr_on.setFont(font)
        self.bt_pwr_off = QPushButton(self.groupBox)
        self.bt_pwr_off.setObjectName(u"bt_pwr_off")
        self.bt_pwr_off.setGeometry(QRect(80, 40, 61, 31))
        self.bt_pwr_off.setFont(font)
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(170, 10, 251, 81))
        self.groupBox_2.setFont(font1)
        self.radioButton_H = QRadioButton(self.groupBox_2)
        self.radioButton_H.setObjectName(u"radioButton_H")
        self.radioButton_H.setGeometry(QRect(20, 40, 81, 25))
        self.radioButton_H.setFont(font)
        self.radioButton_K = QRadioButton(self.groupBox_2)
        self.radioButton_K.setObjectName(u"radioButton_K")
        self.radioButton_K.setGeometry(QRect(100, 40, 81, 25))
        self.radioButton_K.setFont(font)
        self.radioButton_SVC = QRadioButton(self.groupBox_2)
        self.radioButton_SVC.setObjectName(u"radioButton_SVC")
        self.radioButton_SVC.setGeometry(QRect(180, 40, 61, 25))
        self.radioButton_SVC.setFont(font)
        self.bt_initialize2 = QPushButton(Dialog)
        self.bt_initialize2.setObjectName(u"bt_initialize2")
        self.bt_initialize2.setGeometry(QRect(100, 110, 91, 41))
        self.bt_initialize2.setFont(font)
        self.bt_downloadMCD = QPushButton(Dialog)
        self.bt_downloadMCD.setObjectName(u"bt_downloadMCD")
        self.bt_downloadMCD.setGeometry(QRect(200, 110, 121, 41))
        self.bt_downloadMCD.setFont(font)
        self.bt_setDetector = QPushButton(Dialog)
        self.bt_setDetector.setObjectName(u"bt_setDetector")
        self.bt_setDetector.setGeometry(QRect(320, 110, 101, 41))
        self.bt_setDetector.setFont(font)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 170, 121, 171))
        self.groupBox_3.setFont(font1)
        self.radioButton_CDSNoise = QRadioButton(self.groupBox_3)
        self.radioButton_CDSNoise.setObjectName(u"radioButton_CDSNoise")
        self.radioButton_CDSNoise.setGeometry(QRect(10, 100, 111, 25))
        self.radioButton_CDSNoise.setFont(font)
        self.radioButton_FS = QRadioButton(self.groupBox_3)
        self.radioButton_FS.setObjectName(u"radioButton_FS")
        self.radioButton_FS.setGeometry(QRect(10, 130, 111, 25))
        self.radioButton_FS.setFont(font)
        self.radioButton_UTR = QRadioButton(self.groupBox_3)
        self.radioButton_UTR.setObjectName(u"radioButton_UTR")
        self.radioButton_UTR.setGeometry(QRect(10, 40, 111, 25))
        self.radioButton_UTR.setFont(font)
        self.radioButton_CDS = QRadioButton(self.groupBox_3)
        self.radioButton_CDS.setObjectName(u"radioButton_CDS")
        self.radioButton_CDS.setGeometry(QRect(10, 70, 111, 25))
        self.radioButton_CDS.setFont(font)
        self.groupBox_4 = QGroupBox(Dialog)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(140, 170, 281, 171))
        self.groupBox_4.setFont(font1)
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(230, 30, 51, 19))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.label_5.setFont(font2)
        self.label_drops = QLabel(self.groupBox_4)
        self.label_drops.setObjectName(u"label_drops")
        self.label_drops.setGeometry(QRect(160, 30, 61, 20))
        self.label_drops.setFont(font2)
        self.label_drops.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.groupBox_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 30, 51, 19))
        self.label.setFont(font2)
        self.label_2 = QLabel(self.groupBox_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 30, 41, 19))
        self.label_2.setFont(font2)
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(110, 30, 51, 19))
        self.label_3.setFont(font2)
        self.e_reads = QLineEdit(self.groupBox_4)
        self.e_reads.setObjectName(u"e_reads")
        self.e_reads.setGeometry(QRect(10, 50, 41, 26))
        self.e_reads.setFont(font1)
        self.e_resets = QLineEdit(self.groupBox_4)
        self.e_resets.setObjectName(u"e_resets")
        self.e_resets.setGeometry(QRect(60, 50, 41, 26))
        self.e_resets.setFont(font1)
        self.e_groups = QLineEdit(self.groupBox_4)
        self.e_groups.setObjectName(u"e_groups")
        self.e_groups.setGeometry(QRect(110, 50, 41, 26))
        self.e_groups.setFont(font1)
        self.e_drops = QLineEdit(self.groupBox_4)
        self.e_drops.setObjectName(u"e_drops")
        self.e_drops.setGeometry(QRect(160, 50, 61, 26))
        self.e_drops.setFont(font1)
        self.e_ramps = QLineEdit(self.groupBox_4)
        self.e_ramps.setObjectName(u"e_ramps")
        self.e_ramps.setGeometry(QRect(230, 50, 41, 26))
        self.e_ramps.setFont(font1)
        self.label_69 = QLabel(self.groupBox_4)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(10, 92, 61, 20))
        self.label_69.setFont(font2)
        self.label_69.setLayoutDirection(Qt.LeftToRight)
        self.label_69.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_70 = QLabel(self.groupBox_4)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(130, 92, 111, 20))
        self.label_70.setFont(font2)
        self.label_70.setLayoutDirection(Qt.LeftToRight)
        self.label_70.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_exptime = QLineEdit(self.groupBox_4)
        self.e_exptime.setObjectName(u"e_exptime")
        self.e_exptime.setGeometry(QRect(80, 90, 41, 26))
        self.e_exptime.setFont(font2)
        self.e_FS_number = QLineEdit(self.groupBox_4)
        self.e_FS_number.setObjectName(u"e_FS_number")
        self.e_FS_number.setGeometry(QRect(250, 90, 21, 26))
        self.e_FS_number.setFont(font2)
        self.bt_setParam = QPushButton(self.groupBox_4)
        self.bt_setParam.setObjectName(u"bt_setParam")
        self.bt_setParam.setGeometry(QRect(10, 130, 81, 31))
        self.bt_setParam.setFont(font)
        self.bt_acquireramp = QPushButton(self.groupBox_4)
        self.bt_acquireramp.setObjectName(u"bt_acquireramp")
        self.bt_acquireramp.setGeometry(QRect(100, 130, 101, 31))
        self.bt_acquireramp.setFont(font)
        self.bt_stop = QPushButton(self.groupBox_4)
        self.bt_stop.setObjectName(u"bt_stop")
        self.bt_stop.setGeometry(QRect(210, 130, 61, 31))
        self.bt_stop.setFont(font)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"MACIE", None))
        self.bt_initialize1.setText(QCoreApplication.translate("Dialog", u"Initialize1", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Power", None))
        self.bt_pwr_on.setText(QCoreApplication.translate("Dialog", u"On", None))
        self.bt_pwr_off.setText(QCoreApplication.translate("Dialog", u"Off", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Selection", None))
        self.radioButton_H.setText(QCoreApplication.translate("Dialog", u"H-Band", None))
        self.radioButton_K.setText(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.radioButton_SVC.setText(QCoreApplication.translate("Dialog", u"SVC", None))
        self.bt_initialize2.setText(QCoreApplication.translate("Dialog", u"Initialize2", None))
        self.bt_downloadMCD.setText(QCoreApplication.translate("Dialog", u"DownloadMCD", None))
        self.bt_setDetector.setText(QCoreApplication.translate("Dialog", u"SetDetector", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"Sampling Mode", None))
        self.radioButton_CDSNoise.setText(QCoreApplication.translate("Dialog", u"CDS Noise", None))
        self.radioButton_FS.setText(QCoreApplication.translate("Dialog", u"Fowler", None))
        self.radioButton_UTR.setText(QCoreApplication.translate("Dialog", u"Up-The-Ramp", None))
        self.radioButton_CDS.setText(QCoreApplication.translate("Dialog", u"CDS", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Sampling Parameters", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Ramps", None))
        self.label_drops.setText(QCoreApplication.translate("Dialog", u"Drops", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Resets", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Reads", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Groups", None))
        self.label_69.setText(QCoreApplication.translate("Dialog", u"Exp. Time:", None))
        self.label_70.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.bt_setParam.setText(QCoreApplication.translate("Dialog", u"SetParam", None))
        self.bt_acquireramp.setText(QCoreApplication.translate("Dialog", u"AcquireRamp", None))
        self.bt_stop.setText(QCoreApplication.translate("Dialog", u"Stop", None))
    # retranslateUi

